const cors = require('cors')
const express = require('express')
const path = require('path')
const helmet = require('helmet')
const morgan = require('morgan')
const PORT = process.env.PORT || 5000

express()
  .use(helmet())
  .use(morgan('dev'))
  .use(express.json())
  .use(express.urlencoded({extended:true}))
  .use(cors())
  .use('/api', require('./api'))
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'src'))
  .set('view engine', 'html')
  .get('/', (req, res) => res.render('public/index.html'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
